Repository GapLog-2025/gaplog, pull requests merged in 2025-06, with the labels that each got.

#2 init : 프로젝트 디렉토리 생성
  backend/README.md
  frontend/README.md
Labels: documentation

#6 Fe/faet/layout
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Aside.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Layout.tsx
  frontend/src/features/Home/HomeAside.tsx
  frontend/src/index.css
  frontend/src/pages/HomaPage.tsx
  frontend/src/pages/Roadmap.tsx
  frontend/src/router/AppRouter.tsx
  frontend/tailwind.config.ts
Labels: feature, style

#10 Fe/feat/service introduction
  frontend/package-lock.json
  frontend/package.json
  frontend/public/ServiceInfo/step1.png
  frontend/public/ServiceInfo/step2.png
  frontend/public/ServiceInfo/step3.png
  frontend/public/ServiceInfo/step4.png
  frontend/public/ServiceInfo/step5.png
  frontend/src/features/Portfolio/ui/PortfolioPage.tsx
  frontend/src/features/Service/ui/ServiceLoading.tsx
  frontend/src/features/Service/ui/ServicePage.tsx
  frontend/src/pages/ServiceIntroduction.tsx
  frontend/src/router/AppRouter.tsx
Labels: feature

#15 Fe/feat/layout header footer
  frontend/src/components/Aside.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/UserDropdown.tsx
  frontend/src/features/Portfolio/ui/PortfolioPage.tsx
  frontend/src/pages/Service/Contact.tsx
  frontend/src/pages/Service/ServiceIntroduction.tsx
  frontend/src/pages/Service/TeamInfo.tsx
  frontend/src/pages/Support/FAQ.tsx
  frontend/src/pages/Support/Privacy.tsx
  frontend/src/pages/Support/Terms.tsx
  frontend/src/router/AppRouter.tsx
Labels: feature, style, refactor

#19 Fe/feat/homepage aside UI section style
  frontend/src/components/Button.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Tag.tsx
  frontend/src/components/UserCard.tsx
  frontend/src/features/Care/data/CareList.tsx
  frontend/src/features/Care/ui/RecentCareCard.tsx
  frontend/src/features/GapReview/GapStotyList.tsx
  frontend/src/features/GapReview/data/reviewList.tsx
  frontend/src/features/GapReview/ui/ReviewCard.tsx
  frontend/src/features/GapReview/ui/TopReviewCard.tsx
  frontend/src/features/Home/HomeAside.tsx
  frontend/src/features/Home/HomeSection.tsx
  frontend/src/features/Home/ui/card/MessageCard.tsx
  frontend/src/features/Home/ui/card/ServiceInfoCard.tsx
  frontend/src/pages/Test/Jinyoung.tsx
  frontend/src/stores/useAuthStore.ts
  frontend/src/types/emotion.ts
Labels: feature, style, refactor
